<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Connexion</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="output.css">
</head>
<body class="bg-neutral-900 text-white">
    <h1 class="text-2xl font-bold text-center mt-4">Connexion</h1>
    
    <!-- Debug temporaire -->
    <p class="text-yellow-500 text-center">Page login chargée</p>
    <form action="index.php?page=login" method="post">
    <label for="email">Email :</label>
    <input type="email" id="email" name="email"><br><br>
    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password"><br><br>
    <input type="submit" value="Se connecter">
</form>
</body>
</html>
